name: 'Setup Tools'
description: 'Setup tools needed in repo'

runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 22 # semantic-release requires at least this version
    - name: Update npm # To ensure npm 11.5.1 or later is installed for Trusted publishing
      shell: bash
      run: npm install -g npm@latest
    - name: Install dependencies
      shell: bash
      run: npm i