name: 'Setup Tools'
description: 'Setup tools needed in repo'

runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v7
      with:
        node-version: 24
    - name: Install dependencies
      shell: bash
      run: npm i
    - name: Set Xcode 26.0  # minimum support Xcode version by Capacitor 8
      if: runner.os == 'macOS'
      shell: bash
      run: sudo xcode-select --switch /Applications/Xcode_26.0.app